import java.util.*;
import java.sql.*;
import javax.swing.*;
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        view_books_ = new javax.swing.JButton();
        view_staff = new javax.swing.JButton();
        add_books_ = new javax.swing.JButton();
        add_staff__ = new javax.swing.JButton();
        remove_books_ = new javax.swing.JButton();
        remove_staff_ = new javax.swing.JButton();
        log_out_ = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DASHBOARD");

        view_books_.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        view_books_.setText("VIEW BOOKS");
        view_books_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_books_ActionPerformed(evt);
            }
        });

        view_staff.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        view_staff.setText("VIEW STAFF");
        view_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_staffActionPerformed(evt);
            }
        });

        add_books_.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        add_books_.setText("ADD BOOKS");
        add_books_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_books_ActionPerformed(evt);
            }
        });

        add_staff__.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        add_staff__.setText("ADD STAFF");
        add_staff__.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_staff__ActionPerformed(evt);
            }
        });

        remove_books_.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        remove_books_.setText("REMOVE BOOKS");
        remove_books_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_books_ActionPerformed(evt);
            }
        });

        remove_staff_.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        remove_staff_.setText("REMOVE STAFF");
        remove_staff_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_staff_ActionPerformed(evt);
            }
        });

        log_out_.setBackground(new java.awt.Color(0, 255, 204));
        log_out_.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        log_out_.setForeground(new java.awt.Color(153, 0, 0));
        log_out_.setText("Log Out");
        log_out_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_out_ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jButton1.setText("Borrow Books");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jButton2.setText("Books Lent");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(view_books_, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_books_, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remove_books_)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(log_out_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(add_staff__, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(remove_staff_)
                            .addComponent(view_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(view_books_, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(view_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_books_, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_staff__, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(remove_books_, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(remove_staff_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(log_out_, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void view_books_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_books_ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        View_Books ab = new View_Books();
        ab.setVisible(true);
        
        
    }//GEN-LAST:event_view_books_ActionPerformed

    private void add_books_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_books_ActionPerformed
        // TODO add your handling code here:
        this.dispose();
       Add_Books ab = new Add_Books();
       ab.setVisible(true);
       
        
        
    }//GEN-LAST:event_add_books_ActionPerformed

    private void log_out_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_out_ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_log_out_ActionPerformed

    private void view_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_staffActionPerformed
        // TODO add your handling code here:
        this.dispose();
        View_Staff vs = new View_Staff();
        vs.setVisible(true);
    }//GEN-LAST:event_view_staffActionPerformed

    private void add_staff__ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_staff__ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Add_Staff ass = new Add_Staff();
        ass.setVisible(true);
    }//GEN-LAST:event_add_staff__ActionPerformed

    private void remove_books_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_books_ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Delete_Books db = new Delete_Books();
        db.setVisible(true);
    }//GEN-LAST:event_remove_books_ActionPerformed

    private void remove_staff_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_staff_ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Delete_Staff ds = new Delete_Staff();
        ds.setVisible(true);
        
    }//GEN-LAST:event_remove_staff_ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        Borrow_Books bb = new Borrow_Books();
        bb.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Book_Lending bl= new Book_Lending();
        bl.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_books_;
    private javax.swing.JButton add_staff__;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton log_out_;
    private javax.swing.JButton remove_books_;
    private javax.swing.JButton remove_staff_;
    private javax.swing.JButton view_books_;
    private javax.swing.JButton view_staff;
    // End of variables declaration//GEN-END:variables
}
